"""add leave requests module

Revision ID: 82cd948729cf
Revises: 7ae0ebaa6a8c
Create Date: 2026-05-07 16:28:48.238615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cd948729cf'
down_revision: Union[str, Sequence[str], None] = '7ae0ebaa6a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('LEAVE', 'PERMISSION', name='request_category'), nullable=False),
    sa.Column('leave_type', sa.Enum('CA', 'CM', 'CSS', 'CMAT', 'CPAT', 'CEXC', 'CFOR', 'CPAR', name='leave_type'), nullable=True),
    sa.Column('permission_type', sa.Enum('FULL_DAY', 'HALF_DAY', 'HOURLY', name='permission_type'), nullable=True),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_start', sa.String(length=5), nullable=True),
    sa.Column('time_end', sa.String(length=5), nullable=True),
    sa.Column('working_days', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING_MANAGER', 'PENDING_ADMIN', 'APPROVED', 'REJECTED', name='request_status'), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('manager_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('admin_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_category'), 'leave_requests', ['category'], unique=False)
    op.create_index(op.f('ix_leave_requests_requester_id'), 'leave_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_requester_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_category'), table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
